set INTELLEJOS_HOME=D:\Mindstorms\Intellejos_1.0.3
set JAVA_HOME=C:\j2sdk1.4.1_01\bin
set PATH=%PATH%;%JAVA_HOME%
set CLASSPATH=.;%INTELLEJOS_HOME%;%INTELLEJOS_HOME%\robots\;%INTELLEJOS_HOME%\simworlds\